FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install  -y apt-utils 
RUN apt-get install  -y locales

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# Install dependencies
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update --quiet

RUN apt-get install -qq \
    wget \
    software-properties-common \
    gnupg

RUN wget --no-verbose --output-document - https://apt.kitware.com/keys/kitware-archive-latest.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
RUN apt update && apt-get install -qq cmake

RUN apt-get install -qq \
    build-essential \
    gcc \
    automake \
    libcunit1-dev \
    libc++-dev \
    gcc-multilib \
    g++-multilib \
    lsb-release \
    libssl-dev

#RUN wget https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3.tar.gz
#RUN tar xvzf cmake-3.16.3.tar.gz
#RUN cd cmake-3.16.3 && rm -rf Testing/ && ./bootstrap --parallel=4 && make -j4 && make install

RUN wget https://apt.llvm.org/llvm.sh
RUN chmod +x llvm.sh
RUN ./llvm.sh 9

RUN apt-get install -qq \
    clang-tidy-9 \
    clang-format-9 \
    clang-tools-9

# replace dash with bash
RUN cp /bin/bash /bin/sh

# Grab the checked out source
RUN mkdir -p /work
RUN chmod -R 777 /work

WORKDIR /work

