name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: get_clang
      run:  |
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh 
            sudo ./llvm.sh 9
    - name: get clang-tidy
      run:  sudo apt install gcc-c++ clang-tidy-9 clang-format-9 -y
    - name: cmake
      run: pushd tests && cmake . && popd
    - name: make
      run: pushd tests && make && popd
    - name: make test
      run: pushd tests && make test && popd
