name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: get_clang
      run:  |
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh 
            sudo ./llvm.sh 9
    - name: get clang-tidy
      run:  sudo apt install libc++-dev libstdc++-9-dev clang-tidy-9 clang-format-9 -y
    - name: build
      run: |
           pushd tests
           mkdir build
           pushd build
           cmake ..
           make
           make test
           popd
           popd

