name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: get_clang
      run: sudo apt install -qq clang-tools -y
    - name: cmake
      run: pushd tests && cmake . && popd
    - name: make
      run: pushd tests && make && popd
    - name: make test
      run: pushd tests && make test && popd
